sudo: false
dist: xenial
language: node_js
node_js: lts/*

jobs:
  include:
    - if: type = push
      env: TEST_SUITE=visual_tests
    - if: type = push
      env: TEST_SUITE=unit_tests
    - if: type = pull_request
      addons:
        chrome: stable

cache: npm

script:
  if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
    npm test;
  elif [[ "$TEST_SUITE" = "visual_tests" ]]; then
    npm run test:visual;
  else
    npm run test:sauce;
  fi;
