sudo: false
dist: xenial
language: node_js
node_js: lts/*

addons:
  chrome: stable

cache: npm

script:
  if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
    npm test;
  else
    npm run test:sauce;
  fi;
